title: WORSICA
logo: https://github.com/WORSICA/WORSICA.github.io/raw/master/assets/img/logo.png
description: > # this means to ignore newlines until "show_downloads:"
  Water mOnitoRing SentInel Cloud platform.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: https://WORSICA.github.io
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
- .gitignore
- .jekyll-cache
- README.md
